### ISSUE TITLE
Frontend interactivity: Do we need a framework, and if so which one?

### ISSUE THREAD

**Issue by JesseTG** [www-purple/Mixxy#9]
Default/easy styles and layouts in the vein of Bootstrap and Semantic are fine and good, but we may need something like Angular or Backbone for interactivity...or do we?  I'll happily use one if necessary, but let's see if that's the case first

**Comment by JesseTG** [comment]
@k-cleary You mentioned in today's presentation that we would use something like AngularJS.  Would you mind elaborating on that decision?

**Comment by JesseTG** [comment]
@k-cleary How's this coming along?

**Comment by k-cleary** [comment]
I'm still not entirely sure if we'll need one, since we're using disqus and stuff like that, but I think if we do we should use Angular. It seems really easy to use and has a lot of nice features for things like looping through an array of js objects and printing stuff from them. I feel like if we run into a thing where we decide we need it, we should use it

**Comment by JesseTG** [comment]
OK, we'll keep it in our back pocket in case.
